# ADS2288F - October 2nd
> Your first libraries: math and numpy
---

A **library** is a collection of files (called *modules*) tthat contains functions for use by other programs. Python has a *standard library* - what we've been using up until this point - that comes with an expansive list of files and functions for us to use. However, there are many additional libraries for us to call on to do even more in Python.

Libraries open up a world of possibilities in Python that we may not even know exist.  They will assist us, by providing already built functions, in doing more expansive calculations, completing linear algebra tasks, and analysing data.

Two libraries - that do have similar functions - that we will play with today are `math` and `numpy`.

## Your first library - `math`
> Basic math functions not contained in the standard
---

In [1]:
# we begin by telling Python to import this library
import math

`math` contains many mathematical basics that you would expect to be in the standard library, but are not.  This includes square root, trigonometric functions, and even mathematical constants such as $e$ and $\pi$. To call a function within a library we use the same syntax as when we called a method earlier.

In [11]:
# calculate the square root of a number
result = math.sqrt(16)
print(result)

# calculate the area of a circle
r = 12.34
area = math.pi * r**2
print(area)

# calculate the sine and cosine of an angle
result = math.cos(math.pi/2)
print(result) #think of this result as ZERO

if result <= 0.0000000000000001:
    result = 0
print(result)


# use e and log
result = math.e ** 2
print(result)

result = math.log(2) #this is calculating 'ln(2)'
print(result)

4.0
478.3879062809779
6.123233995736766e-17
0
7.3890560989306495
0.6931471805599453


## Your second library - `numpy`
> "numerical python"
---

`numpy` is another library in Python that can handle various mathematical basics. In fact, it uses a lot of the same commands as `math` does.  

We introduce `numpy` to replace `math` - but also see that, often, programmers get lazy and don't want to have to type `numpy` tons of times in their program.  We often create an nickname (or *alias*) for libraries, so that when we call them later on, we have a short form.  Each library has a *standard* alias, but you can name them whatever you like.

In [15]:
# import numpy with its standard alias
import numpy as np

Now that we have imported `numpy` into Python - we can go ahead an use it.

In [18]:
# calculate the square root of a number
print(np.sqrt(16))

# calculate the area of a circle
r = 12.34
print(np.pi*r**2)

# calculate the sine and cosine of an angle
result = np.cos(np.pi/2)
print(result)


# use e and log



4.0
478.3879062809779
6.123233995736766e-17


Why we use `numpy` over `math` - most of the time - is it contains additional functions that allow us to do more.  For instance, `numpy` encodes some basic statistical functions and some basic linear algebra functions.

In [25]:
# create a list of test scores
scores = [76,73,96,65,55,66]

# use numpy to compute the mean, median and standard deviation of the list
print(np.mean(scores))
print(np.median(scores))
print(np.std(scores)) 



71.83333333333333
69.5
12.694049349553076


To do "proper" linear algebra - we need to use `numpy` arrays.  These will encode in Python as traditional vectors or matrices.  We will still use list (and list of list) syntax introduced earlier.  However, we will now tell Python that these objects are arrays.

In [29]:
# create the vector (1,2,3,4) as a numpy array and check its type
vector = np.array([1,2,3,4])
print(vector)
print(type(vector))

# create two matrices as numpy arrays
matrix1 = np.array([[1,2], [3,4]])
matrix2 = np.array([[5,6], [7,8]])
print(matrix1)


[1 2 3 4]
<class 'numpy.ndarray'>
[[1 2]
 [3 4]]


In [41]:
# Matrix Multiplication
mult = np.matmul(matrix1,matrix2)
print(mult)

# Matrix Transpose
transpose = np.transpose(matrix1)
print(transpose)

# Matrix Inverse - the weird one
inverse = np.linalg.inv(matrix1)
print(inverse)


[[19 22]
 [43 50]]
[[1 3]
 [2 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


Both of these libraries are even more expansive than what has been shown here.  A *fun* bit of programming is discovering exactly what each library can do.  Each library has their own extensive online page.  For instance, for `numpy`, we can head to https://numpy.org/doc/stable/reference/ to get tons of help on what this library can do.


### Discussion time...
In a small group, read through this documentation and find one or two things that `numpy` can do to share with the class.

### General Program Structure

When you are creating a program, there is often a standard structure we follow.  Your program should have the following *order* to it.

1. Library imports
2. Function definitions and/or the importing of data sets
3. Variable definitions
4. Actual program

### Lab Assignment Style Question
---
You are a manager at a retail store, and you want to analyze the sales data for the past month to identify the following:

- The total sales for the month.
- The average daily sales.
- The number of days with above-average sales.

Create functions to compute the total sales for a month (`total_sales`) and the average daily sales (`average_sales`) - each should have one parameter called `sales`.  Use a loop to compute the number of days with above-average sales. Print for the user - the total monthly sales, the average daily sales and the number of days with above-average sales.

In [3]:
# import the numpy library
import numpy as np

# function definitions
def total_sales(sales):
    return np.sum(sales)  #computes the MEAN of a list
    
def average_sales(sales):
    return np.mean(sales)

# daily sales (given)
daily_sales = [1200, 1450, 1100, 900, 1350, 1600, 1550, 1400, 1250, 1100, 1300, 1500, 1650, 1400, 1200, 1250]

# computations of total montly sales and average sales
total = total_sales(daily_sales)
average = average_sales(daily_sales)


# determine the number of days with above-average sales
ctr = 0
for i in daily_sales:
    if i > average:
           ctr += 1

# print results
print(total)
print(average)
print(ctr)

21200
1325.0
8


In [62]:
#practive qs:

sales_data = np.array([45000, 48000, 52000, 60000, 55000, 61000, 68000, 72000, 69000, 75000, 80000, 85000])

# a. Calculate the total sales for the company.
total_sales = np.sum(sales_data)
print("Total Sales:", total_sales)

# b. Calculate the average sales per month.
average_sales = np.mean(sales_data)
print("Average Sales per Month:", average_sales)

# c. Find the month with the highest sales.
highest_sales_month = np.argmax(sales_data) + 1  # Adding 1 because months are 1-based.
print("Month with Highest Sales:", highest_sales_month)

# d. Calculate the standard deviation of sales.
sales_std_dev = np.std(sales_data)
print("Standard Deviation of Sales:", sales_std_dev)

Total Sales: 770000
Average Sales per Month: 64166.666666666664
Month with Highest Sales: 12
Standard Deviation of Sales: 12212.243401148247


[35000 34000 35000 38000 37000 39000 41000 42000 43000 45000 47000 51000]
40583.333333333336


In [2]:
#PROFIT CALCULATION

def calculate_profits(expenses, revenues):
    return revenues - expenses

def calculate_average_profits(profits):
    return np.mean(profits)

# Given monthly expenses and revenues
expenses = np.array([25000, 28000, 30000, 32000, 31000, 33000, 34000, 35000, 36000, 37000, 38000, 39000])
revenues = np.array([60000, 62000, 65000, 70000, 68000, 72000, 75000, 77000, 79000, 82000, 85000, 90000])

# Calculate monthly profits
profits = calculate_profits(expenses, revenues)

# Calculate the average monthly profit
average_profit = calculate_average_profits(profits)

print("Monthly Profits:")
print(profits)
print("Average Monthly Profit:", average_profit)

NameError: name 'np' is not defined

In [73]:
product_prices = np.array([10, 20, 15, 25, 30])
quantities_sold = np.array([100, 75, 120, 50, 80])


#calculate total rev from each product and total revenue for the store

def calculate_rev(product_prices, quantities_sold):
    return product_prices * quantities_sold

def calculate_total_rev(revenue):
    return np.sum(revenue)

revenue = calculate_rev(product_prices, quantities_sold)
total_revenue = calculate_total_rev(revenue)


print(revenue)
print(total_revenue)

[1000 1500 1800 1250 2400]
7950


In [74]:
customer_ages = np.array([28, 35, 42, 24, 50, 33, 29, 38, 45, 31])
purchase_amounts = np.array([100, 200, 150, 75, 250, 180, 120, 220, 280, 160])

#Calculate the average age of customers and the average purchase amount.
avg_age = np.mean(customer_ages)
avg_purchase = np.mean(purchase_amounts)

print(avg_age)
print(avg_purchase)

35.5
173.5


In [81]:
sales_data = np.array([45000, 48000, 52000, 60000, 55000, 61000, 68000, 72000, 69000, 75000, 80000, 85000])

#Calculate the month-over-month growth rate for each month.

growth_rate = np.diff(sales_data) / sales_data[:-1] * 100

print(growth_rate)
print(sales_data[:-1])

[ 6.66666667  8.33333333 15.38461538 -8.33333333 10.90909091 11.47540984
  5.88235294 -4.16666667  8.69565217  6.66666667  6.25      ]
[45000 48000 52000 60000 55000 61000 68000 72000 69000 75000 80000]
